Repository 2023-Winter-Bootcamp-Team-I/Docker, pull requests merged in 2024-01, with the labels that each got.

#10 bugfix: share 버튼 클릭시 오류 해결
  frontend/src/pages/LibraryPage.tsx
Labels: bug

#14 메인페이지 button, 스토리 선택 페이지 애니메이션 적용
  frontend/src/components/CreateTitleModal.tsx
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/SignUp.tsx
  frontend/src/pages/StoryChoiceModal.tsx
Labels: documentation

#17 feat/#9
  frontend/src/components/FrontCover.tsx
  frontend/src/components/NavBar.tsx
  frontend/src/components/ShareModal.tsx
  frontend/src/i18n.ts
  frontend/src/pages/BackCoverPage.tsx
  frontend/src/pages/FrontCoverPage.tsx
Labels: enhancement

#28 온보딩 페이지 추가
  backend/grafana/grafana.db
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/images/CreateInfoPage.png
  frontend/src/assets/images/createBookPage.png
  frontend/src/assets/images/mainPage.png
  frontend/src/i18n.ts
  frontend/src/pages/AboutUsPage.tsx
  frontend/src/utils/Routes.tsx
  frontend/tailwind.config.js
Labels: enhancement
